CONFIG_ZMK_SPLIT_BLE_PREF_LATENCY=0
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

# base
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0
# qwerty
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=0
# nav
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=2
# num
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=4
# sym
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
# func
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=3
# mouse
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=5
# game1
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=0
# game2
CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=0
# game3
CONFIG_RGBLED_WIDGET_LAYER_9_COLOR=0
