CONFIG_ZMK_STUDIO=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=1
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=4
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=3
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=0
