CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SLEEP=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=1

CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

CONFIG_BT_DEVICE_NAME="CloudSplit36"

CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=100

CONFIG_ZMK_SPLIT_BLE_PREF_LATENCY=0
CONFIG_ZMK_USB=y
CONFIG_ZMK_STUDIO=n

CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

# base
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0
# qwerty
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=0
# nav
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=2
# num
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=4
# sym
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
# func
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=3
# mouse
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=5
# game1
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=0
# game2
CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=0
# game3
CONFIG_RGBLED_WIDGET_LAYER_9_COLOR=0
